AllCops:
  Exclude:
    - ./features/support/hooks.rb
    - ./features/support/env.rb
    - ./features/support/report.rb
    - ./features/step_definitions/*.rb

Metrics/LineLength:
  Max: 160

MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 200
